# Generated by Django 4.2.20 on 2026-06-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('flag_url', models.URLField(blank=True)),
                ('season', models.IntegerField(default=2026)),
                ('is_tracked', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_score_ht', models.IntegerField(blank=True, null=True)),
                ('away_score_ht', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TBD', 'To Be Defined'), ('NS', 'Not Started'), ('1H', 'First Half'), ('HT', 'Half Time'), ('2H', 'Second Half'), ('ET', 'Extra Time'), ('BT', 'Break Time'), ('P', 'Penalty'), ('SUSP', 'Suspended'), ('INT', 'Interrupted'), ('FT', 'Full Time'), ('AET', 'After Extra Time'), ('PEN', 'Penalty Shootout'), ('PST', 'Postponed'), ('CANC', 'Cancelled'), ('ABD', 'Abandoned'), ('AWD', 'Technical Loss'), ('WO', 'WalkOver'), ('LIVE', 'Live')], db_index=True, default='NS', max_length=10)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('referee', models.CharField(blank=True, max_length=100)),
                ('round', models.CharField(blank=True, max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team')),
            ],
            options={
                'ordering': ['-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('OWN_GOAL', 'Own Goal'), ('PENALTY', 'Penalty'), ('MISSED_PENALTY', 'Missed Penalty'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('YELLOW_RED', 'Second Yellow'), ('SUB', 'Substitution'), ('VAR', 'VAR Decision'), ('HT', 'Half Time'), ('FT', 'Full Time')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('minute', models.IntegerField()),
                ('minute_extra', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('player_api_id', models.IntegerField(blank=True, null=True)),
                ('assist_name', models.CharField(blank=True, max_length=100)),
                ('assist_api_id', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('alerted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='matches.team')),
            ],
            options={
                'ordering': ['minute', 'minute_extra'],
                'unique_together': {('match', 'event_type', 'minute', 'player_name')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'kickoff'], name='matches_mat_status_712a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition', 'kickoff'], name='matches_mat_competi_e7d907_idx'),
        ),
    ]
